### PR TITLE
Prepare for release 0.4

### PR DESCRIPTION
**Pull request by CharliePoole**
This PR updates the CHANGES file and changes version numbers for the release. If there is anything missing that should be included in the release, please add comment.

I expressly held back any changes to how the files are organized for after the release.

### CODE REVIEW

**Comment by CharliePoole** [comment]
In testing, I saw we have been including a spurious `.addins` file that points to extensions, which aren't present! We'll eventually put back an `.addins` file, but it will need to really point at something!

**Comment by grokky1** [comment]
@CharliePoole Does this work with .NET Core?

**Comment by CharliePoole** [comment]
@grokky1 Not yet. The GUI uses the NUnit engine so it will work with .NET Core when the engine does, that is, at the same time the console runner can run .NET Core tests. Right now, we are focusing primarily on UI design, but we will keep up with new engine versions as they come out.

**Comment by grokky1** [comment]
@CharliePoole Sounds good.

It's a real pain to use VS' "Test Explorer" which is slow and cumbersome. Can't wait for this gui runner (and the console runner) to support Core!

**Pull request merged**
