### PR TITLE
Copy nunit-agent.exe and nunit-agent-x86.exe to output

### LINKED ISSUE #184: The path is not of a legal form exception on load
after cloning the latest (currently a69848e202b1dc7fdaa960679ee4f55d39df7106) when opening an assembly I get the title's message. So far I've tried two assemblies, I've tried one of my work test assemblies and I tried mock-assembly and both give me the same exception (see stack trace at end). When I debug the path is empty string. Getting the outerXml of the test node gives me
```
?testNode.Xml.OuterXml.ToString()
"<test-suite type=\"Assembly\" id=\"0\" name=\"\" fullname=\"\" runstate=\"NotRunnable\" testcasecount=\"1\" result=\"Failed\" label=\"Error\" start-time=\"2017-05-18 12:50:51Z\" end-time=\"2017-05-18 12:50:51Z\" duration=\"0.001\" total=\"1\" passed=\"0\" failed=\"1\" inconclusive=\"0\" skipped=\"0\" asserts=\"0\"><failure><message><![CDATA[NUnit components for version 4.0.30319 of the CLR are not installed\r\nParameter name: targetRuntime]]></message><stack-trace><![CDATA[   at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)\r\n   at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)\r\n   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()\r\n   at NUnit.Engine.Runners.ProcessRunner.Explore(TestFilter filter)]]></stack-trace></failure></test-suite>"
```
I'm not sure what the outer components are that it speaks of as I've never seen that exception before. However I can run both assemblies tests outside of nunit-gui including nunit-console
```
System.ArgumentException occurred
  HResult=0x80070057
  Message=The path is not of a legal form.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at NUnit.Gui.Presenters.TestPropertiesPresenter.GetTestType(TestNode testNode) in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\TestPropertiesPresenter.cs:line 146
   at NUnit.Gui.Presenters.TestPropertiesPresenter.DisplayTestProperties() in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\TestPropertiesPresenter.cs:line 84
   at NUnit.Gui.Presenters.TestPropertiesPresenter.OnSelectedItemChanged(ITestItem testItem) in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\TestPropertiesPresenter.cs:line 64
   at NUnit.Gui.Presenters.TestPropertiesPresenter.<WireUpEvents>b__4_4(TestItemEventArgs ea) in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\TestPropertiesPresenter.cs:line 57
   at NUnit.Gui.Model.TestItemEventHandler.Invoke(TestItemEventArgs args)
   at NUnit.Gui.Model.TestModel.NotifySelectedItemChanged(ITestItem testItem) in C:\github\nunit\nunit-gui\src\nunit-gui\Model\TestModel.cs:line 332
   at NUnit.Gui.Presenters.TreeViewPresenter.<WireUpEvents>b__6_14(TreeNode tn) in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\TreeViewPresenter.cs:line 115
   at NUnit.UiKit.Elements.TreeViewElement.<.ctor>b__3_0(Object s, TreeViewEventArgs e) in C:\github\nunit\nunit-gui\src\nunit.uikit\Elements\TreeViewElement.cs:line 49
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, IntPtr lparam)
   at System.Windows.Forms.TreeView.set_SelectedNode(TreeNode value)
   at NUnit.UiKit.Elements.TreeViewElement.<>c__DisplayClass26_0.<Add>b__0() in C:\github\nunit\nunit-gui\src\nunit.uikit\Elements\TreeViewElement.cs:line 176
   at NUnit.UiKit.Elements.ControlElement`1.InvokeIfRequired(MethodInvoker del) in C:\github\nunit\nunit-gui\src\nunit.uikit\Elements\ControlElement.cs:line 87
   at NUnit.UiKit.Elements.TreeViewElement.Add(TreeNode treeNode, Boolean doClear) in C:\github\nunit\nunit-gui\src\nunit.uikit\Elements\TreeViewElement.cs:line 169
   at NUnit.UiKit.Elements.TreeViewElement.Add(TreeNode treeNode) in C:\github\nunit\nunit-gui\src\nunit.uikit\Elements\TreeViewElement.cs:line 141
   at NUnit.Gui.Presenters.NUnitTreeDisplayStrategy.OnTestLoaded(TestNode testNode) in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\NUnitTreeDisplayStrategy.cs:line 68
   at NUnit.Gui.Presenters.TreeViewPresenter.<WireUpEvents>b__6_0(TestNodeEventArgs ea) in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\TreeViewPresenter.cs:line 69
   at NUnit.Gui.Model.TestNodeEventHandler.Invoke(TestNodeEventArgs args)
   at NUnit.Gui.Model.TestModel.LoadTests(IList`1 files) in C:\github\nunit\nunit-gui\src\nunit-gui\Model\TestModel.cs:line 227
   at NUnit.Gui.Presenters.MainPresenter.OnOpenProjectCommand() in C:\github\nunit\nunit-gui\src\nunit-gui\Presenters\MainPresenter.cs:line 177
   at NUnit.UiKit.Elements.MenuElement.<.ctor>b__9_0(Object <p0>, EventArgs <p1>) in C:\github\nunit\nunit-gui\src\nunit.uikit\Elements\MenuElement.cs:line 41
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at NUnit.Gui.Program.Main(String[] args) in C:\github\nunit\nunit-gui\src\nunit-gui\Program.cs:line 97
```

### PR DESCRIPTION
**Pull request by mikkelbu**
Fixes #184

### CODE REVIEW

**Comment by immeraufdemhund** [comment]
Do we want to add it like that or use our build scripts to add it?

**Comment by mikkelbu** [comment]
Actually, I had not thought about using the build scripts for copying the files. As the build scripts are now the `nunit-agent*.exes` and associated configs will not be handled by the `"PackageZip"` task.

On one hand it will be cleaner to have all the handling of these files happen in the build scripts, but on the other hand then this will make it impossible to compile and run from visual studio (without copying the files in some other way).

**Comment by immeraufdemhund** [comment]
I guess if it was solely my project I would say put it in the build scripts and "catch the exception" from the xml to display to the user a more meaningful message other than the path is incorrect. Cause when you debug you first think it's the assembly you just loaded, and getting the xml from the TestNode was not my first thought.

**Comment by mikkelbu** [comment]
I agree that we also should handle the error better in the user interface. @CharliePoole Do you have any opinion on how to copy the files to the output folder? (and can you answer the last sentence in the previous comment)

**Comment by CharliePoole** [comment]
I think the problem that @immeraufdemhund is raising has to do with packaging, which we do not yet do. The script should make sure that all the needed binaries are in the package, just like any packaging script. But your current problem, if I understand has to do with running in the build environment.

I imagine that you are running into a problem that we have with all our runners that use the engine. The engine is distributed as a library, so everything gets referenced and the referenced assemblies are copied to the output directory. However, we don't want to reference the agents from the gui, we only want them to be present. I deal with this by removing the references after the packages are added. Something has happened locally on your system such that the agents have actually been removed. I suggest removing and re-adding the package to see what happens.

I think the true solution to this lies in how the engine is packaged, not the gui.

**Comment by immeraufdemhund** [comment]
to test that theory I pulled the latest and ran git clean -fxd to remove any and all things not checked in. Ran cake and tested again. problem persists. poked around in tools/ and packages/ and found agent floating around in both of those. Copied agent over to bin/ and naturally it worked as expected. So that means there could be two fixes.. One is this pull request and 2 would be to copy it in after it is built. (like either from msbuild or the build script)

Out of curiosity how would "fixing" packaging in the engine fix how the binaries get copied over?

**Comment by CharliePoole** [comment]
My longer term goal is to have only the engine app in lib and the rest of
the engine in tools. For now this fix is the right thing to do.

I was suggesting, however, that you not just fix the .csproj file manually,
but rather let nuget fix it by re-installing the package.

**Comment by immeraufdemhund** [comment]
huh. Yeah I ran NuGet with -reinstall and got similar diff as this PR:
```
     <ApplicationIcon>nunit.ico</ApplicationIcon>
   </PropertyGroup>
   <ItemGroup>
     <Reference Include="Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756, processorArchitecture=MSIL">
       <HintPath>..\..\packages\NUnit.Engine.3.6.1\lib\Mono.Cecil.dll</HintPath>
-      <Private>True</Private>
+    </Reference>
+    <Reference Include="nunit-agent, Version=3.6.1.0, Culture=neutral, processorArchitecture=MSIL">
+      <HintPath>..\..\packages\NUnit.Engine.3.6.1\lib\nunit-agent.exe</HintPath>
+    </Reference>
+    <Reference Include="nunit-agent-x86, Version=3.6.1.0, Culture=neutral, processorArchitecture=x86">
+      <HintPath>..\..\packages\NUnit.Engine.3.6.1\lib\nunit-agent-x86.exe</HintPath>
     </Reference>
     <Reference Include="nunit.engine, Version=3.6.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
       <HintPath>..\..\packages\NUnit.Engine.3.6.1\lib\nunit.engine.dll</HintPath>
-      <Private>True</Private>
     </Reference>
     <Reference Include="nunit.engine.api, Version=3.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
       <HintPath>..\..\packages\NUnit.Engine.3.6.1\lib\nunit.engine.api.dll</HintPath>
-      <Private>True</Private>
     </Reference>
     <Reference Include="System" />
     <Reference Include="System.Drawing" />
     <Reference Include="System.Windows.Forms" />
     <Reference Include="System.Xml" />
```

**Comment by CharliePoole** [comment]
Yes, the reinstall puts it back the way it was before accidentally merged in the commit that removed it. The big difference is that your fix is adding the config files, which doesn't happen with our normal nuget install of the engine. Looking at what's in those configs, it occurs to me that we should really have them. In fact the absence of the configs may just explain why we have certain kinds of unexplained behavior under the agent in some installations. I'll write an issue on that.

I'm going to merge your change, but we may want to experiment and make further changes. In particular, if a user does a package re-install, does anything change? For ease in figuring out problems, we would like it to be set up in such a way that everything works the same way (1) initially, (2) after a re-install and (3) in our CI builds.

**Pull request merged**
