### PR TITLE
Fixes #68 

### LINKED ISSUE #68: Implement XML view of test details.
The XML tab of the GUI display is currently empty.

### PR DESCRIPTION
**Pull request by iCodeIT**
Do not merge yet.

Fixes #68 <== This gives us a link to the issue plus a backlink from the issue to this PR.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Just going to bed, will review tomorrow.

**Comment by CharliePoole** [comment]
This looks good to me. I'd be OK with either waiting or merging it as is, while you continue to work on the formatting and coloring of the XML.

**Comment by iCodeIT** [comment]
I’m fine either way. It will be a couple of days until I have time to finish this, so if you need it now go ahead and merge it.

**Comment by CharliePoole** [comment]
I'll go ahead and merge it. I'm working on some changes that will merge more smoothly later if I get your new presenter into the build right away.

We have not had much luck in reusing PRs once they are merged but you can create a new PR from the same branch and referring to the same issue.

**Pull request merged**
